// Column inventories from unpatched beta50 internal/migrations.ts.
export const v2Columns = {
  effect_agent_schedules: [
    "tenant_id",
    "owner_id",
    "schedule_id",
    "deadline_at_millis",
    "record_json",
  ],
  effect_agent_subscription_sequences: [
    "tenant_id",
    "source_address",
    "sequence",
    "event_scan_cursor",
    "delivery_scan_cursor",
    "recovery_scan_cursor",
  ],
  effect_agent_subscriptions: [
    "tenant_id",
    "source_address",
    "owner_id",
    "subscription_id",
    "ordinal",
    "source_name",
    "source_version",
    "matching_key",
    "state",
    "expires_at_millis",
    "recovery_at_millis",
    "record_json",
  ],
  effect_agent_subscription_events: [
    "tenant_id",
    "source_address",
    "event_id",
    "source_name",
    "source_version",
    "matching_key",
    "payload_digest",
    "cutoff",
    "cursor",
    "routing_complete",
    "next_attempt_at_millis",
    "record_json",
  ],
  effect_agent_subscription_deliveries: [
    "tenant_id",
    "source_address",
    "owner_id",
    "subscription_id",
    "event_id",
    "delivery_key",
    "state",
    "next_attempt_at_millis",
    "record_json",
  ],
} as const;
