import { Schema } from "effect";

export const SqlStorageFailpointLocation = Schema.Literals([
  "materialize:before",
  "materialize:after",
  "append:before",
  "append:after-batch-insert",
  "append:after-record-insert",
  "append:after-tail-update",
  "append:after",
  "export:after-thread-read",
  "save-checkpoint:before",
  "save-checkpoint:after",
  "ledger:admit:before",
  "ledger:admit:after",
  "ledger:mark-ready:before",
  "ledger:mark-ready:after",
  "ledger:claim:before",
  "ledger:claim:after",
  "ledger:mark-input-applied:before",
  "ledger:mark-input-applied:after",
  "ledger:renew:before",
  "ledger:renew:after",
  "ledger:finalize-settlement:before",
  "ledger:finalize-settlement:after",
  "ledger:request-abort:before",
  "ledger:request-abort:after",
  "ledger:release:before",
  "ledger:release:after",
  "ledger:claim-joining:before",
  "ledger:claim-joining:after",
  "ledger:mark-joined:before",
  "ledger:mark-joined:after",
  "ledger:revert-joining:before",
  "ledger:revert-joining:after",
  "ledger:suspend:before",
  "ledger:suspend:after",
  "ledger:approval-decision:before",
  "ledger:approval-decision:after",
  "ledger:mark-unknown:before",
  "ledger:mark-unknown:after",
  "ledger:unknown-resolution:before",
  "ledger:unknown-resolution:after",
  "ledger:child-reservation:before",
  "ledger:child-reservation:after",
  "ledger:child-attach:before",
  "ledger:child-attach:after",
  "ledger:child-release-pending:before",
  "ledger:child-release-pending:after",
  "ledger:child-release:before",
  "ledger:child-release:after",
  "ledger:child-settled:before",
  "ledger:child-settled:after",
]);

export type SqlStorageFailpointLocation = typeof SqlStorageFailpointLocation.Type;
